name: Generate OpenTofu Plan

on:
  issue_comment:

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    name: Create OpenTofu Plan (${{ matrix.app }} / ${{ matrix.env }})
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    environment: tofu-production

    strategy:
      fail-fast: false
      matrix:
        app: [web1, web2]
        env: [production, staging]
        exclude:
          - app: web2
            env: staging

    steps:
      - name: Checkout code from `main` (safe and reviewed)
        # (the checkout from `main` is cause by `pull_request_target`)
        uses: actions/checkout@v4

      - name: Checkout this PR's `.infrastructure` directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: tmp_pr_content
          sparse-checkout: |
            .infrastructure

      - name: Import the `.infrastructure` from this PR
        run: |
          rsync -a --delete tmp_pr_content/.infrastructure/ .infrastructure/

      - name: Version
        run: echo v3

      - name: Tofu Plan
        uses: dflook/tofu-plan@v2
        env:
          TF_INPUT: "0"
          VERCEL_API_TOKEN: ${{ secrets.PLAN_SECRETS_VERCEL_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_passphrase: ${{ secrets.TF_VAR_PASSPHRASE }}
        with:
          add_github_comment: changes-only
          path: .infrastructure/${{ matrix.app }}
          label: ${{ matrix.app }}/${{ matrix.env }}
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/${{ matrix.app }}/env/${{ matrix.env }}.tfvars
