name: Generate OpenTofu Plan

on:
  pull_request:
    paths:
      - ".infrastructure/**"
      - ".github/workflows/opentofu_*"

permissions:
  contents: read
  pull-requests: write

env:
  TF_INPUT: "0"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_passphrase: ${{ secrets.TF_VAR_PASSPHRASE }}

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: tofu-plan
    name: ${{ matrix.app.name }} - Create OpenTofu Plan

    strategy:
      fail-fast: false
      matrix:
        app:
          - name: Web1
            dir: web1
            env: [production, staging]

          - name: Web2
            dir: web2
            env: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: ${{ matrix.app.name }} - Tofu Plan
        uses: dflook/tofu-plan@v2
        env:
          VERCEL_API_TOKEN: ${{ secrets.PLAN_SECRETS_VERCEL_API_TOKEN }}
        with:
          add_github_comment: changes-only
          path: .infrastructure/${{ matrix.app.dir }}
          label: ${{ matrix.app.dir }}/${{ matrix.app.env }}
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/${{ matrix.app.dir }}/env/${{ matrix.app.env }}.tfvars
