name: Apply OpenTofu Plan

on:
  push:
    branches:
      - main
    paths:
      - ".infrastructure/**"

permissions:
  contents: read
  pull-requests: write

env:
  TF_INPUT: "0"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
  TF_VAR_passphrase: ${{ secrets.TF_VAR_PASSPHRASE }}

jobs:
  apply-web1:
    runs-on: ubuntu-latest
    name: Web1 - Apply approved plan

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: tofu apply
        uses: dflook/tofu-apply@v2
        with:
          path: .infrastructure/web1
          label: production
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/web1/env/production.tfvars

  apply-web2:
    runs-on: ubuntu-latest
    name: Web2 - Apply approved plan

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: tofu apply
        uses: dflook/tofu-apply@v2
        with:
          path: .infrastructure/web2
          label: production
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/web1/env/production.tfvars
