name: Generate OpenTofu Plan

on: 
  pull_request:
    paths:
      - ".infrastructure/**"
      - ".github/workflows/opentofu_*"


permissions:
  contents: read
  pull-requests: write

env:
  TF_INPUT: "0"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_passphrase: ${{ secrets.TF_VAR_PASSPHRASE }}

jobs:
  plan-web1:
    runs-on: ubuntu-latest
    environment: tofu-plan
    name: Web1 - Create OpenTofu Plan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Web1 - Tofu Plan
        uses: dflook/tofu-plan@v2
        env:
          VERCEL_API_TOKEN: ${{ secrets.PLAN_SECRETS_VERCEL_API_TOKEN }}
        with:
          add_github_comment: changes-only
          path: .infrastructure/web1
          label: web1/production
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/web1/env/production.tfvars

  plan-web2:
    runs-on: ubuntu-latest
    environment: tofu-plan
    name: Web2 - Create OpenTofu Plan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Web2 - Tofu Plan
        uses: dflook/tofu-plan@v2
        env:
          VERCEL_API_TOKEN: ${{ secrets.PLAN_SECRETS_VERCEL_API_TOKEN }}
        with:
          add_github_comment: changes-only
          path: .infrastructure/web2
          label: web2/production
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/web2/env/production.tfvars
