name: Apply OpenTofu Plan

on:
  push:
    branches:
      - main
    paths:
      - ".infrastructure/**"
      - ".github/workflows/opentofu_*"

permissions:
  contents: read
  pull-requests: write

env:
  # `GITHUB_TOKEN` is automatically set as secret by GitHub when
  # starting a workflow, so we don't need to add it manually
  TF_INPUT: "0"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VERCEL_API_TOKEN: ${{ secrets.VERCEL_ACCOUNT_TOKEN }}
  TF_VAR_VERCEL_API_TOKEN: ${{ secrets.VERCEL_ACCOUNT_TOKEN }}
  TF_VAR_passphrase: ${{ secrets.TF_VAR_PASSPHRASE }}
  TF_VAR_my_secret_var: ${{ secrets.TF_VAR_MY_SECRET_VAR }}

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply approved Plan (${{ matrix.app }} / ${{ matrix.env }})
    environment: tofu-production

    strategy:
      fail-fast: false
      matrix:
        app: [web1, web2]
        env: [production]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Debug token presence
        run: |
          if [ -z "${TF_VAR_vercel_api_token}" ]; then
            echo "TF_VAR_vercel_api_token is EMPTY"
            exit 1
          else
            echo "TF_VAR_vercel_api_token is set (length: ${#TF_VAR_vercel_api_token})"
          fi

      - name: tofu apply
        uses: dflook/tofu-apply@v2
        with:
          path: .infrastructure/${{ matrix.app }}
          label: ${{ matrix.app }}/${{ matrix.env }}
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/${{ matrix.app }}/env/${{ matrix.env }}.tfvars

  deploy-after-changes:
    needs: [apply]
    name: Deploy to Vercel after IaC changes
    runs-on: ubuntu-latest
    environment: tofu-production

    strategy:
      fail-fast: false
      matrix:
        app: [web1]
        env: [production]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Gathering Tofu Output
        uses: dflook/tofu-output@v2
        id: tf-outputs
        with:
          path: .infrastructure/${{ matrix.app }}
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/${{ matrix.app }}/env/${{ matrix.env }}.tfvars

      - name: Trigger Vercel Deploy Hook
        run: |
          curl -s -X POST "${{ steps.tf-outputs.outputs.tofu_web1_deploy_hook_url }}" \
            --fail \
            --show-error
