name: Generate OpenTofu Plan

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

env:
  TF_INPUT: "0"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
  TF_VAR_passphrase: ${{ secrets.TF_VAR_PASSPHRASE }}

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create OpenTofu Plan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Tofu Plan
        uses: dflook/tofu-plan@v2
        with:
          add_github_comment: changes-only
          path: .infrastructure
          label: production
          var_file: .infrastructure/env/production.tfvars
