name: Generate OpenTofu Plan

on:
  pull_request:
    paths:
      - ".infrastructure/**"
      - ".github/workflows/opentofu_*"

permissions:
  contents: read
  pull-requests: write

env:
  TF_INPUT: "0"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_passphrase: ${{ secrets.TF_VAR_PASSPHRASE }}

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: tofu-plan
    name: Create OpenTofu Plan (${{ matrix.app }} / ${{ matrix.env }})

    strategy:
      fail-fast: false
      matrix:
        app: [web1, web2]
        env: [production, staging]
        exclude:
          - app: web2
            env: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Tofu Plan
        uses: dflook/tofu-plan@v2
        env:
          VERCEL_API_TOKEN: ${{ secrets.PLAN_SECRETS_VERCEL_API_TOKEN }}
        with:
          add_github_comment: changes-only
          path: .infrastructure/${{ matrix.app }}
          label: ${{ matrix.app }}/${{ matrix.env }}
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/${{ matrix.app }}/env/${{ matrix.env }}.tfvars
