name: Apply OpenTofu Plan

on:
  push:
    branches:
      - main
    paths:
      - ".infrastructure/**"
      - ".github/workflows/opentofu_*"

permissions:
  contents: read
  pull-requests: write

env:
  TF_INPUT: "0"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
  TF_VAR_passphrase: ${{ secrets.TF_VAR_PASSPHRASE }}

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply approved Plan (${{ matrix.app }} / ${{ matrix.env }})

    strategy:
      fail-fast: false
      matrix:
        app: [web1, web2]
        env: [production]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: tofu apply
        uses: dflook/tofu-apply@v2
        with:
          path: .infrastructure/${{ matrix.app }}
          label: ${{ matrix.app }}/${{ matrix.env }}
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/${{ matrix.app }}/env/${{ matrix.env }}.tfvars
