name: Generate OpenTofu Plan

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  plan:
    name: Create OpenTofu Plan (${{ matrix.app }} / ${{ matrix.env }})
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'tofu plan' }}
    runs-on: ubuntu-latest
    environment: tofu-production

    strategy:
      fail-fast: false
      matrix:
        app: [web1, web2]
        env: [production, staging]
        exclude:
          - app: web2
            env: staging

    steps:
      - name: Checkout code from `main` (safe and reviewed)
        uses: actions/checkout@v4

      - name: Debug gr√íanted permissions (headers)
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const res = await github.request('GET /repos/{owner}/{repo}', { owner, repo });
            core.info(`x-accepted-github-permissions: ${res.headers['x-accepted-github-permissions'] || ''}`);
            core.info(`x-oauth-scopes: ${res.headers['x-oauth-scopes'] || ''}`);
            core.info(`x-accepted-oauth-scopes: ${res.headers['x-accepted-oauth-scopes'] || ''}`);

      - name: Debug granted permissions (PAT)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_READ_TOKEN }}
          script: |
            const res = await github.request('GET /repos/{owner}/{repo}', { owner: context.repo.owner, repo: context.repo.repo });
            core.info(`x-accepted-github-permissions: ${res.headers['x-accepted-github-permissions'] || ''}`);
            core.info(`x-oauth-scopes: ${res.headers['x-oauth-scopes'] || ''}`);

            
      - name: Load PR metadata
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const issue_number = context.payload.issue.number;

            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: issue_number,
            });

            core.setOutput("head_sha", pr.head.sha);
            core.setOutput("base_sha", pr.base.sha);

      - name: Checkout this PR's `.infrastructure` directory
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.head_sha }}
          path: tmp_pr_content
          sparse-checkout: |
            .infrastructure

      - name: Import the `.infrastructure` from this PR
        run: |
          rsync -a --delete tmp_pr_content/.infrastructure/ .infrastructure/

      - name: Version
        run: echo v4

      - name: Tofu Plan
        uses: dflook/tofu-plan@v2
        env:
          TF_INPUT: "0"
          VERCEL_API_TOKEN: ${{ secrets.PLAN_SECRETS_VERCEL_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_passphrase: ${{ secrets.TF_VAR_PASSPHRASE }}
        with:
          add_github_comment: changes-only
          path: .infrastructure/${{ matrix.app }}
          label: ${{ matrix.app }}/${{ matrix.env }}
          backend_config: ../common/_backend_config.tfvars
          var_file: .infrastructure/${{ matrix.app }}/env/${{ matrix.env }}.tfvars
