name: Test Secret Access

on:
  pull_request_target:
  push:
    branches:
      - main

env:
  TARGET_SECRET: ${{ secrets.PLAN_SECRETS_VERCEL_API_TOKEN }}

jobs:
  plan:
    environment: tofu-production
    runs-on: ubuntu-latest
    # environment: tofu-production # for later
    name: Check whether a secret exists in the current environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Version
        run: echo v1

      - name: Assess availability
        run: test -n "$TARGET_SECRET"
